version: 1
jobs:
  build:
    docker:
      - image: hosoden/hello-world:1.0
    steps:
      - checkout
      - run: docker build -t hosoden/hello-world:1.0 .
workflow:
  version: 1
  build:
    jobs:
      - build

