version: 1.0
jobs:
  build:
    docker: 
      - image: hosoden/hello-world:latest # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      # - run: echo "hello world" # run the `echo` command
      - run: ocker build -t hosoden/hello-world:latest .
